# Week 8 Overview

This week will be a mix of data joining/merging problems and linear algebra. 
The first 5 problems are data cleaning and the final 4 problems are linear algebra. 

There are multiple ways to combine data. These methods are common cross multiple languages like pandas, SQL, and R. At times the naming is different but the general concepts apply. 

### **Joining or Merging**
This is a process of combining two datasets by adding the columns of one dataset to the other by some logical relationship between the columns. 

In SQL we call this joining but pandas has two functions:

**merge** - The default behavor for merge is to combine on columns matching.

**join** - The default behavor for join is to combine on the column index matching. 

Often times I will colloquially use the word "join" for either merging or joining in pandas. 

Left Dataset
| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |

Right Dataset
| key    | different_value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

Data Joined on key

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | cat |
| A2 | $80     | dog |
| A3    | $420    | apple |

Typically we refer to the starting dataset as the left dataset and the one being added as the right. 

The logic is typically that there is the same value in a specific column in both datasets. SQL allows for slightly more advanced logic which we will learn next quarter. Today we will focus on just columns matching. 

There are different types of joins that you will explore in this notebook (inner, outer, left, right, cross). The typical visual that is used to illustration these concepts in Ven Diagrams. If you are getting stuck trying to pick the right join type search for "types of joins" and look at the pictures that come up.


## **Concat or Union**

This is a process of combining two dataset by adding the rows of one dataset to the end of another. There is no logic required for this. This is called conact in pandas and union in SQL. 

In most version of SQL you are required to have the same columns in both datasets. In pandas you don't have to. If I concatenate the two dataset above in pandas I would get:

| key    | value | different_value |
| -------- | ------- | ------- |
| A1  | $250    | null |
| A2 | $80     | null |
| A3    | $420    | null |
| A1  | null    | cat |
| A2 | null     | dog |
| A3    | null    | apple |

However if my right dataset looked like this:

| key    | value |
| -------- | ------- |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |

then I could union them in SQL or concat in pandas to get:

| key    | value |
| -------- | ------- |
| A1  | $250    |
| A2 | $80     |
| A3    | $420    |
| A1  | cat    |
| A2 | dog     |
| A3    | apple    |



In [58]:
import pandas as pd
import numpy as np

In [59]:
df_1 = pd.DataFrame({"ints": range(100)})
df_2 = pd.DataFrame({"ints": range(-10, 10)}, index=range(-10, 10))


df_1['threes'] = np.floor(df_1['ints']/3) * 3

df_2['evens'] = df_2['ints']*2
df_2['threes'] = np.floor(df_2['ints']/3) * 3

### Problem 1:

Your first task will be to create a dataset by `merging` `df_1` and `df_2` on the `ints` column where the match on both sides. The results will be a dataframe with 10 rows and 5 columns.

You will then create the same dataframe by using the `join` function and joining the two datasets where the indexes are equal. There will be a little more work of handle column duplication so look up the error and figure out arguments to set. How many columns do you get in this case?

In [60]:
pd.merge(df_1, df_2, on = 'ints')

,ints,threes_x,evens,threes_y
0,0,0.0,0,0.0
1,1,0.0,2,0.0
2,2,0.0,4,0.0
3,3,3.0,6,3.0
4,4,3.0,8,3.0
5,5,3.0,10,3.0
6,6,6.0,12,6.0
7,7,6.0,14,6.0
8,8,6.0,16,6.0
9,9,9.0,18,9.0


In [61]:
df_1.join(df_2, on = 'ints', lsuffix='_left', rsuffix='_right')

,ints,ints_left,threes_left,ints_right,evens,threes_right
0,0,0,0.0,0.0,0.0,0.0
1,1,1,0.0,1.0,2.0,0.0
2,2,2,0.0,2.0,4.0,0.0
3,3,3,3.0,3.0,6.0,3.0
4,4,4,3.0,4.0,8.0,3.0
...,...,...,...,...,...,...
95,95,95,93.0,NaN,NaN,NaN
96,96,96,96.0,NaN,NaN,NaN
97,97,97,96.0,NaN,NaN,NaN
98,98,98,96.0,NaN,NaN,NaN


## Problem 2:

Next you will perform the same merge as above three times with the following modifications:

* You want to keep all rows in `df_1` even if there is no match found in `df_2`
* You want to keep all rows in `df_2` even if there is no match found in `df_1`
* You want to keep all rows in `df_1` and `df_2` even if there is no match found in the other dataframe


How many rows do you end up with in each case? 

Think through a scenario where you might want to do this and add it as a comment above each merge. 

In [62]:
pd.merge(df_1, df_2, how='left', on = 'ints')

,ints,threes_x,evens,threes_y
0,0,0.0,0.0,0.0
1,1,0.0,2.0,0.0
2,2,0.0,4.0,0.0
3,3,3.0,6.0,3.0
4,4,3.0,8.0,3.0
...,...,...,...,...
95,95,93.0,NaN,NaN
96,96,96.0,NaN,NaN
97,97,96.0,NaN,NaN
98,98,96.0,NaN,NaN


In [63]:
pd.merge(df_1, df_2, how='right', on = 'ints')

,ints,threes_x,evens,threes_y
0,-10,NaN,-20,-12.0
1,-9,NaN,-18,-9.0
2,-8,NaN,-16,-9.0
3,-7,NaN,-14,-9.0
4,-6,NaN,-12,-6.0
5,-5,NaN,-10,-6.0
6,-4,NaN,-8,-6.0
7,-3,NaN,-6,-3.0
8,-2,NaN,-4,-3.0
9,-1,NaN,-2,-3.0


In [64]:
pd.merge(df_1, df_2, how='outer', on = 'ints')

,ints,threes_x,evens,threes_y
0,-10,NaN,-20.0,-12.0
1,-9,NaN,-18.0,-9.0
2,-8,NaN,-16.0,-9.0
3,-7,NaN,-14.0,-9.0
4,-6,NaN,-12.0,-6.0
...,...,...,...,...
105,95,93.0,NaN,NaN
106,96,96.0,NaN,NaN
107,97,96.0,NaN,NaN
108,98,96.0,NaN,NaN


### Problem 3

Now we are going to merge on columns that are not the same. Merge on the following:

* Merge `df_1` and `df_2` where `df_1.ints = df_2.evens`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, only keep rows where there is a value for either dataframe
* Merge `df_1` and `df_2` where `df_1.ints = df_2.threes`, keep all rows from `df_1` even if there is no match found in `df_2`
* Merge `df_1` and `df_2` where `df_1.threes = df_2.threes`, only keep rows where there is a value for either dataframe


How many rows do you end up with in each case? Are there any duplications? (try: value_count)

Think through a scenario where you might want to do this and add it as a comment above each merge. 

In [65]:
pd.merge(df_1, df_2, left_on= 'ints', right_on= 'evens')

,ints_x,threes_x,ints_y,evens,threes_y
0,0,0.0,0,0,0.0
1,2,0.0,1,2,0.0
2,4,3.0,2,4,0.0
3,6,6.0,3,6,3.0
4,8,6.0,4,8,3.0
5,10,9.0,5,10,3.0
6,12,12.0,6,12,6.0
7,14,12.0,7,14,6.0
8,16,15.0,8,16,6.0
9,18,18.0,9,18,9.0


In [66]:
pd.merge(df_1, df_2, left_on= 'ints', right_on= 'threes')

,ints_x,threes_x,ints_y,evens,threes_y
0,0,0.0,0,0,0.0
1,0,0.0,1,2,0.0
2,0,0.0,2,4,0.0
3,3,3.0,3,6,3.0
4,3,3.0,4,8,3.0
5,3,3.0,5,10,3.0
6,6,6.0,6,12,6.0
7,6,6.0,7,14,6.0
8,6,6.0,8,16,6.0
9,9,9.0,9,18,9.0


In [67]:
pd.merge(df_1, df_2, how='left', left_on= 'ints', right_on= 'threes')

,ints_x,threes_x,ints_y,evens,threes_y
0,0,0.0,0.0,0.0,0.0
1,0,0.0,1.0,2.0,0.0
2,0,0.0,2.0,4.0,0.0
3,1,0.0,NaN,NaN,NaN
4,2,0.0,NaN,NaN,NaN
...,...,...,...,...,...
101,95,93.0,NaN,NaN,NaN
102,96,96.0,NaN,NaN,NaN
103,97,96.0,NaN,NaN,NaN
104,98,96.0,NaN,NaN,NaN


In [68]:
pd.merge(df_1, df_2, left_on= 'threes', right_on= 'threes')

,ints_x,threes,ints_y,evens
0,0,0.0,0,0
1,0,0.0,1,2
2,0,0.0,2,4
3,1,0.0,0,0
4,1,0.0,1,2
5,1,0.0,2,4
6,2,0.0,0,0
7,2,0.0,1,2
8,2,0.0,2,4
9,3,3.0,3,6


### Problem 4

Add a new the column to `df_2` called `threes_string` that is the `threes` column converted to a string. Attempt to merge `df_1` and `df_2` where `df_1.threes = df_2.threes_string` with an inner join. What happens? Why?

In [69]:
df_2['threes_string'] = df_2['threes'].astype(str)
pd.merge(df_1, df_2, how='inner', left_on='threes', right_on='threes_string')

ValueError: You are trying to merge on float64 and object columns for key 'threes'. If you wish to proceed you should use pd.concat

We are attempting to merge on two different data types, so equality cannot be found.

### Problem 5

Now you will play around with `pd.concat` by doing the following:

* Concatenate `df_1` and `df_2` keeping all rows, columns and indexes
* Concatenate `df_1` and `df_2` keeping all rows and columns but ignore the indexes from the orginal dataframes and instead have the index on this dataframe be zero to the number of rows.
* Concatenate `df_1` and `df_2` keeping all rows and indexes the same but only keeping columns that exist in both dataframes


In [ ]:
pd.concat([df_1, df_2])

,ints,threes,evens
0,0,0.0,NaN
1,1,0.0,NaN
2,2,0.0,NaN
3,3,3.0,NaN
4,4,3.0,NaN
...,...,...,...
5,5,3.0,10.0
6,6,6.0,12.0
7,7,6.0,14.0
8,8,6.0,16.0


In [ ]:
pd.concat([df_1, df_2]).reset_index(drop=True)

,ints,threes,evens
0,0,0.0,NaN
1,1,0.0,NaN
2,2,0.0,NaN
3,3,3.0,NaN
4,4,3.0,NaN
...,...,...,...
115,5,3.0,10.0
116,6,6.0,12.0
117,7,6.0,14.0
118,8,6.0,16.0


In [ ]:
pd.concat([df_1, df_2], join='inner')

,ints,threes
0,0,0.0
1,1,0.0
2,2,0.0
3,3,3.0
4,4,3.0
...,...,...
5,5,3.0
6,6,6.0
7,7,6.0
8,8,6.0


## Linear Algebra: Rank and Column Space

### Problem 6
You will now learn how to create random matrices with arbitrary rank (subject to the constraints about matrix sizes, etc.). To create an $m \times n$ matrix with rank $r$, multiply a random $m \times r$ matrix with a random $r \times n$ matrix. Implement this in Python and confirm that the rank is indeed $r$. 

What happens if you set $r > min{M,N}$, and why does that happen?

In [71]:
m, n, r = 5, 4, 3
M = np.random.rand(m, r)
N = np.random.rand(r, n)
product = np.dot(M, N)
computed_rank = np.linalg.matrix_rank(product)
print(product)
print(computed_rank)

[[0.9555827  1.25966035 0.89038804 1.08670209]
 [0.4462797  0.63234888 0.46076747 0.40956451]
 [0.12604139 0.6576643  0.62928231 0.70627864]
 [0.35461582 0.59350677 0.46092514 0.42862236]
 [0.53687903 0.759173   0.55274773 0.49926073]]
3


In [72]:
r1 = 5
M1 = np.random.rand(m, r1)
N1 = np.random.rand(r1, n)
product1 = np.dot(M1, N1)
computed_rank1 = np.linalg.matrix_rank(product1)
print(f"With r = {r}, m = {m}, and n = {n}:\t{computed_rank}")
print(f"With (r1 = {r1})  > min(m, n):\t{computed_rank1}")

With r = 3, m = 5, and n = 4:	3
With (r1 = 5)  > min(m, n):	4


### Problem 7
Interestingly, the matrices $A$, $A^T$, $A^T A$, and $AA^T$ all have the same rank. Write code to demonstrate this, using random matrices of various sizes, shapes (square, tall, wide), and ranks. Create a total of 6 random, two of each size that have different sizes and ranks. 

In [73]:
def test_rank(name, A):
    T = "\u1d40"
    print(f"The ranks of matrix {name}:")
    print(f"A: {np.linalg.matrix_rank(A)}\t\
            A{T}: {np.linalg.matrix_rank(A.T)}\t\
            A{T}A: {np.linalg.matrix_rank(np.dot(A.T, A))}\t\
            AA{T}: {np.linalg.matrix_rank(np.dot(A, A.T))}")
    
rand1 = np.random.rand(4,4)
rand2 = np.random.rand(6,6)
rand3 = np.random.rand(2,7)
rand4 = np.random.rand(4,13)
rand5 = np.random.rand(7,3)
rand6 = np.random.rand(72,26)
test_rank("rand1", rand1)
test_rank("rand2", rand2)
test_rank("rand3", rand3)
test_rank("rand4", rand4)
test_rank("rand5", rand5)
test_rank("rand6", rand6)

The ranks of matrix rand1:
A: 4	            Aᵀ: 4	            AᵀA: 4	            AAᵀ: 4
The ranks of matrix rand2:
A: 6	            Aᵀ: 6	            AᵀA: 6	            AAᵀ: 6
The ranks of matrix rand3:
A: 2	            Aᵀ: 2	            AᵀA: 2	            AAᵀ: 2
The ranks of matrix rand4:
A: 4	            Aᵀ: 4	            AᵀA: 4	            AAᵀ: 4
The ranks of matrix rand5:
A: 3	            Aᵀ: 3	            AᵀA: 3	            AAᵀ: 3
The ranks of matrix rand6:
A: 26	            Aᵀ: 26	            AᵀA: 26	            AAᵀ: 26


### Problem 8

Demonstrate the addition rule of matrix rank $(r(A + B) ≤ r(A) + r(B))$ by creating three pairs of rank-1 matrices that have a sum with 
1. rank-0
2. rank-1
3. rank-2

Then repeat this exercise using matrix multiplication instead of addition.

In [74]:
a = np.matrix([[0, 0], [1, 1]])
b = np.matrix([[0, 0], [-1, -1]])
c = np.matrix([[1, 1], [2, 2]])
d = np.matrix([[0, 2], [0, 3]])

rank_a = np.linalg.matrix_rank(a)
rank_b = np.linalg.matrix_rank(b)
rank_c = np.linalg.matrix_rank(c)
rank_d = np.linalg.matrix_rank(d)

a_b = a + b
rank_a_b = np.linalg.matrix_rank(a_b)
a_c = a + c
rank_a_c = np.linalg.matrix_rank(a_c)
a_d = a + d
rank_a_d = np.linalg.matrix_rank(a_d)

print(f"Ranks for matrices: a = {rank_a}, b = {rank_b}, c = {rank_c}, and d = {rank_d}.")
print(f"When added, a + b = {rank_a_b}, a + c = {rank_a_c}, and a + d = {rank_a_d}.")

Ranks for matrices: a = 1, b = 1, c = 1, and d = 1.
When added, a + b = 0, a + c = 1, and a + d = 2.


### Problem 9

The goal of this exercise is to answer the question is $v \in C(A)$?

Create a rank-3 matrix $A \in \mathbb{R}^{4 \times 3}$ and vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. 

Follow the algorithm described in the [In the Column Space?](https://learning.oreilly.com/library/view/practical-linear-algebra/9781098120603/ch06.html#id335) section of Practical Linear Algebra to determine whether the vector is in the column space of the matrix. 

Rerun the code multiple times to see whether you find a consistent pattern. 

Next, use a $A \in \mathbb{R}^{4 \times 4}$ rank-4 matrix and a vector $v \in \mathbb{R}^{4}$ using numbers randomly drawn from a normal distribution. What happens in this case? Why?


In [113]:
A = np.random.standard_normal((4, 3))
v = np.random.standard_normal((4,1))
A1 = np.concatenate([A, v], axis=1)
print(v)
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(v))
print(np.linalg.matrix_rank(A1))

[[ 1.38829065]
 [ 0.01782187]
 [-0.67254997]
 [-0.31541918]]
3
1
4


In [138]:
B = np.random.standard_normal((4, 4))
u = np.random.standard_normal((4,1))
B1 = np.concatenate([B, u], axis=1)
print(u)
print(np.linalg.matrix_rank(B))
print(np.linalg.matrix_rank(u))
print(np.linalg.matrix_rank(B1))

[[-0.46634641]
 [-0.42795863]
 [ 0.21422692]
 [-1.43360912]]
4
1
4
